spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # 환경변수 없으면 local 기본

  config:
    import:
      - "https://${CONFIG_REPO_TOKEN}@raw.githubusercontent.com/Geun-Hwan/balanceLab-config/main/application-${spring.profiles.active}.yml"
